dist: trusty
sudo: required
language: generic
cache: apt

install:
  - sudo add-apt-repository -y ppa:v-launchpad-jochen-sprickerhof-de/pcl
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake libvtk5-dev libpcl-1.7-all-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  
